config/routes.rb
AuthDemo::Application.routes.draw do
  
  root to: "static_pages#home"
  resource :session, only: [:create, :destroy, :new]
  resource :user, only: [:create, :new, :show] do
    resource :counter, only: [:update]
  end
  get '/home' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  post '/contact' => 'static_pages#create_contact_message'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  validates :name, :email, :subject, :message, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    # no user with given username    
    return nil if user.nil?

    # check user's password
    user.password_digest.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :logged_in?, :current_user

  def current_user
    # fetches the user we've logged in as
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by(session_token: self.session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end

  def log_in!(user)
    # force other clients to log out by regenerating token
    user.reset_session_token!
    # log this client in
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  def update
    current_user.counter = params[:user][:counter]
    current_user.save!
    redirect_to user_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # signs a user in
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      # no user with the given name!
      render :new
    else
      # sign the user in
      log_in!(@user)
      redirect_to user_url
    end
  end

  def destroy
    # sign a user out
    log_out!
    redirect_to home_url
  end

  def new
    # presents a login form
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
  def contact
  end
  
  def create_contact_message
    @contact = Contact.new(contact_params)
    unless @contact.save
      flash.now[:errors] = @contact.errors.full_messages
    else
      flash.now[:success] = ["Success. We will never respond to your message"]
    end
    render :contact
  end
  
  def about
  end
  
  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to user_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    # show the user's details (just their username)
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = current_user
    render :show
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AuthDemo</title>
	<%= stylesheet_link_tag 'application' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>

</head>
<body data-spy data-target>
	
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
				
				
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					
					<% if !logged_in? %>
					<li>
						<a href='<%= new_user_url %>'>Sign Up</a>
					</li>
					<li>
						<a data-toggle="modal" data-target="#sign-in-modal">Sign In
						</a>
					</li>
					<% else %>
					<li>
						<%= link_to "Profile", user_url %>
					</li>
					<li>
						<%= link_to "Sign Out", session_url, method: :delete %>
					</li>
					<% end %>
	
					<li>
						<a href='<%= home_url %>'>Home</a>
					</li>
					<li>
						<a href='<%= about_url %>'>About</a>
					</li>
					<li>
						<a href='<%= contact_url %>'>Contact</a>
					</li>
					<li>
						<a href='#streets'>Streets</a>
					</li>
					<li>
						<a href='#shower'>Shower</a>
					</li>
					<li>
						<a href='#nomads'>Nomads</a>
					</li>
					<li>
						<a href='#community'>Community</a>
					</li>
				</ul>
			</div>
		
		</div>
	</nav>
	
	<% if flash[:success] %>
	<div class="alert alert-success" role="alert"> <%= flash[:success].join("\n") %> </div>
	<% end %>
		
	<% if flash[:errors] %>
	<div class="alert alert-danger" role="alert"> <%= flash[:errors].join("\n") %> </div>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>

	<div class="modal fade" id="sign-in-modal">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title">Log in!</h4>
				</div>
				<div class="modal-body">
				
					<%= render "sessions/new" %>
				
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->


</body>
</html>

app/views/static_pages/about.html.erb
<div class="row">
	<div class="jumbotron">
		<div class="container">
			<h1> About Us</h1>
			<div class="col-md-6">
				<h2>We make your nightly sleep selection easy, satisfaction guaranteed!</h2>
			</div>
		
			<div class="col-md-6">
				<h2>Choose from hundreds of sleep selections, from the beaches of Santa Monica, to under your local bridge.</h2>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<h1> How We Started</h1>
	<p> Our team has been through the challenges of homelessness for decades, and we've found that it is really hard to find a place to sleep without a network of kind-hearted hosts who don't mind a piss-stained stench pervading their home atmosphere. We have created a wonderful community for both homeless and hosts that are out of town.
	</p>	
</div>

<div class="row">
	<div class="col-xs-4">
		<img src="https://lh5.googleusercontent.com/-w9h6uwffsyk/AAAAAAAAAAI/AAAAAAAAAHg/Y6wZl7N58hM/photo.jpg" class="img-responsive img-rounded" alt="Responsive image">
		<h2> Anastasia Zorko</h2>
		<p>Survived the cold homeless life of mother Russia. That's hardcore! </p>
	</div>
	<div class="col-xs-4">
		<img src="https://avatars3.githubusercontent.com/u/628429?v=2&s=460" class="img-responsive img-rounded" alt="Responsive image">
		<h2> Daniel Burt</h2>
		<p> Lived on the beach in Santa Monica. </p>
	</div>
	<div class="col-xs-4">
		<img src="http://stuffpoint.com/cats/image/245258-cats-cute-white-cat.jpg" class="img-responsive img-rounded" alt="Responsive image">
		<h2>Breakfast the Homeless Cat </h2>
		<p> Got lost and never found his first owners again. </p>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class="wrapper">
	<div class="row">
	
		<div class="col-xs-4 col-xs-offset-1">
			<h3> Contact Us </h3>
			<form action="<%= contact_url  %>" method="POST" role="form">
	
				<input
				type="hidden"
				name="authenticity_token"
				value="<%= form_authenticity_token %>">
  
				<label>Personal Information </label>
	
				<div class="row">
					<div class="col-xs-9">
						<div class="form-group">
							<label for="name">Full Name</label>
							<input class="form-control" type="text" name="contact[name]" id="name">
							<br>
						</div>
					</div>
				</div>
  
				<div class="row">
					<div class="col-xs-9">
						<div class="form-group">
							<label for="email">Email Address</label>
							<input class="form-control" type="text" name="contact[email]" id="email">
							<br>
						</div>
					</div>
				</div>
	
				<label>What can we help you with? </label>
	
				<div class="row">
					<div class="col-xs-9">
						<div class="form-group">
							<label for="subject">Subject</label>
							<input class="form-control" type="text" name="contact[subject]" id="subject">
							<br>
						</div>
					</div>
				</div>
	
				<div class="row">
					<div class="col-xs-9">
						<div class="form-group">
							<label for="message">Message</label>
							<textarea class="form-control" name="contact[message]" id="message"> </textarea>
							<br>
						</div>
					</div>
				</div>

				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
 
		<div class="col-xs-4">
			<h3> Founders </h3>
		
			<table class="table">
				<tr>
					<th> Co-Founder </th>
					<th> Number</th>
				</tr>
				<tr>
					<td> Anastasia Zorko</td>
					<td>(408)9121-324 </td>
				</tr>
				<tr>
					<td> Daniel Burt</td>
					<td>(408)3576-324 </td>
				</tr>
			</table>
		</div>
	
	</div>
</div>
		

app/views/static_pages/home.html.erb
<h1 class="text-center"> Hobo-n-b </h1>
<div class="row">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" max-width="600" max-height="400">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox" max-width="600" max-height="400">
			<div class="item active" >
				<img src="http://4.bp.blogspot.com/-OhzdwDz4WJg/TuA5lFAzorI/AAAAAAAAET0/k_hCjlrxLL4/s1600/990843841_3122f7afa6.jpg" alt="Homeless" width="600" height="400" >
				<div class="carousel-caption">
					<h4> No more sitting on the street.</h4>
				</div>
			</div>
		
			<div class="item">
				<img src="http://robertnielsen21.files.wordpress.com/2013/08/homeless_reading_on_the_sidewalk.jpg" alt="Homeless" width="600" max-height="400">
				<div class="carousel-caption">
					<h4> Say goodbye to shopping cart luggage.</h4>
				</div>
			</div>
		
			<div class="item">
				<img src="http://www.minnpost.com/sites/default/files/imagecache/article_detail/images/articles/HomelessMan640_0.jpg" alt="Homeless" width="600" height="400">
				<div class="carousel-caption">
					<h4> Don't get waken up by car exhaust.</h4>
				</div>
			</div>
		
		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
</div>

<div class="row">
	<div class="col-xs-6 col-xs-offset-3" data-spy="scroll" data-target=".navbar-example">
		<h4 id="streets">We get you off the streets. </h4>
		<p>Kielbasa pancetta sausage capicola, chuck pork chicken shank flank kevin ribeye shoulder. Pork loin chuck venison jowl swine bresaola t-bone strip steak prosciutto. Chicken turducken tongue pastrami jowl. Tenderloin bacon jowl, ham hock shankle beef ribs tongue short loin chicken pastrami jerky prosciutto. </p>
	</div>
</div>
		<div class="row">
	<div class="col-xs-6 col-xs-offset-3" data-spy="scroll" data-target=".navbar-example">
		<h4 id="shower"> You might even get to shower. </h4>
		<p>Bacon ipsum dolor amet turducken venison ham jowl, pastrami <strong data-toggle="tooltip" data-placement="top" title="Yummy!">filet mignon</strong> bresaola tongue short loin shank pork loin. Pork belly bresaola venison salami, tail frankfurter andouille pancetta tenderloin corned beef ball tip rump. Meatloaf beef ribs andouille meatball shank, chuck tongue. Shoulder spare ribs pastrami jowl. Hamburger spare ribs salami turkey, short loin doner rump tri-tip andouille leberkas shoulder jowl ground round landjaeger. Prosciutto jerky brisket capicola. </p>
	</div>
</div>

<div class="row">
<div class="col-xs-6  col-xs-offset-3" data-spy="scroll" data-target=".navbar-example">
	<h4 id="community" > Make connections with our community of hosts and homeless. </h4>
	<p>Frankfurter venison ham hock tongue pork pig prosciutto porchetta landjaeger flank leberkas short ribs. Jerky beef sausage biltong ground round strip steak. Beef swine shank, salami prosciutto turkey sausage. Spare ribs chicken turducken beef ribs, porchetta rump drumstick tri-tip prosciutto hamburger pancetta t-bone pastrami. </p>
</div>
</div>

<div class="row">
<div class="col-xs-6 col-xs-offset-3" data-spy="scroll" data-target=".navbar-example">
	<h4 id="nomads"> Become a better nomadic human being. </h4>
	<p>Kevin corned beef shankle, pig pancetta kielbasa landjaeger beef sirloin biltong t-bone tri-tip tenderloin chuck doner. Pork chop salami fatback, pork loin tri-tip beef tenderloin short ribs swine leberkas flank. Cow shank spare ribs, swine pork loin venison shoulder short loin meatloaf boudin chicken sirloin turkey tri-tip. Ground round hamburger flank, bresaola filet mignon pork chop spare ribs pig pork loin jerky. Tail sirloin shank filet mignon. Doner corned beef ham hock, pork chop ribeye andouille porchetta short ribs ground round sausage salami pork belly. </p>
</div>
</div>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip();
})
</script>
			
</div>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<ul>
  <% @user.errors.full_messages.each do |err_msg| %>
    <li><%= err_msg %></li>
  <% end %>
</ul>

<form action="/user" method="POST" role="form">
 	<input
 	type="hidden"
 	name="authenticity_token"
 	value="<%= form_authenticity_token %>">
  
 	<div class="row">
 		<div class="col-xs-4">
 			<div class="form-group">
 				<label for="user_username">Username</label>
 				<input class="form-control" type="text" name="user[username]" id="user_username">
 				<br>
 			</div>
 		</div>
 	</div>
  
 	<div class="row">
 		<div class="col-xs-4">
 			<div class="form-group">
 				<label for="user_password">Password</label>
 				<input class="form-control" type="password" name="user[password]" id="user_password">
 				<br>
 			</div>
 		</div>
 	</div>

 	<button type="submit" class="btn btn-primary">Create User!</button>
 </form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, <%= @user.username %></p>